### PR TITLE
Remove monkey patches for SparkSession

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR partially addresses https://github.com/databricks/spark-pandas/issues/90

> koalas: parallel to pandas namespace. Includes I/O functions (read_csv, read_parquet) as well as general functions (e.g. concat, get_dummies).

It removes monkey-patches from Spark session and only targets to allow:

```python
from databricks import koalas

koalas.read_csv
koalas.read_parquet
koalas.to_datetime
koalas.from_pandas
koalas.get_dummies
```

- Remove `session.py`

- Move implementations into `namespace.py` (which are exposed via `databricks/koalas/__init__.py`)

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Seems it's failing due to download failure:

```
Could not reach https://dist.apache.org/repos/dist/release//spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz
Content of /home/travis/.cache/spark-versions/spark-2.4.0-bin-hadoop2.7:
ls: cannot access /home/travis/.cache/spark-versions/spark-2.4.0-bin-hadoop2.7: No such file or directory
```

**Comment by rxin** [comment]
LGTM.

**Comment by ueshin** [comment]
I'd merge this. Thanks!

**Comment by HyukjinKwon** [comment]
Thank you guys.

**Pull request merged**
